spring:
  primary:
    datasource:
      driver: org.h2.Driver
      url: jdbc:h2:file:~/src/main/resources/primary
      username: sa
      password: 
  replica:
    datasource:
      driver: org.h2.Driver
      url: jdbc:h2:file:~/src/main/resources/primary
      username: sa
      password: 
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect 
    properties:
      hibernate:
        ddl-auto: create-drop
        show-sql: true
        temp:
          use_jdbc_metadata_defaults: false
  h2:
    console:
      enabled: true
#flyway:
#  locations: classpath:db  
  
